name        : cmake
version     : 3.2.2
release     : 7
source      :
    - http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz : ade94e6e36038774565f2aed8866415443444fb7a362eb0ea5096e40d5407c78
homepage    : http://www.cmake.org/
license     :
    - BSD
summary     : CMake is a cross-platform, open-source build system.
description : |
    CMake, the cross-platform, open-source make system. CMake is used to control the software compilation process using simple platform and compiler independent configuration files. CMake generates native makefiles and workspaces that can be used in the compiler environment of your choice.
builddeps  :
    - pkgconfig(libarchive)
clang      : no
patterns   :
    - /usr/share/cmake*
    - docs: /usr/share/doc
setup      : |
    # Unable to find use for jsoncpp in Solus yet, + circle deps..
    ./configure --prefix=/usr \
               --system-libs \
               --no-system-jsoncpp \
               --no-qt-gui \
               --docdir=/share/doc/cmake-3.2
    # Docdir... Cmon cmake sort your life out
build      : |
    %make
install    : |
    %make_install
