name       : cmake
version    : 3.6.2
release    : 8
source     :
    - http://www.cmake.org/files/v3.6/cmake-3.6.2.tar.gz : 189ae32a6ac398bb2f523ae77f70d463a6549926cde1544cd9cc7c6609f8b346
homepage   : http://www.cmake.org/
license    :
    - BSD
summary    : CMake is a cross-platform, open-source build system.
description: |
    CMake, the cross-platform, open-source make system. CMake is used to control the software compilation process using simple platform and compiler independent configuration files. CMake generates native makefiles and workspaces that can be used in the compiler environment of your choice.
builddeps  :
    - pkgconfig(libarchive)
clang      : no
patterns   :
    - /usr/share/cmake*
    - /usr/share/aclocal*
    - docs : /usr/share/doc
setup      : |
    # Unable to find use for jsoncpp in Solus yet, + circle deps..
    ./configure --prefix=/usr \
               --system-libs \
               --no-system-jsoncpp \
               --no-qt-gui \
               --docdir=/share/doc/cmake-3.2
    # Docdir... Cmon cmake sort your life out
build      : |
    %make
install    : |
    %make_install
