name       : cmake
version    : 3.12.2
release    : 18
source     :
    - https://cmake.org/files/v3.12/cmake-3.12.2.tar.gz : 0f97485799e51a7070cc11494f3e02349b0fc3a24cc12b082e737bf67a0581a4
homepage   : https://www.cmake.org/
license    : BSD-3-Clause
component  : system.devel
summary    : CMake is a cross-platform, open-source build system.
description: |
    CMake, the cross-platform, open-source make system. CMake is used to control the software compilation process using simple platform and compiler independent configuration files. CMake generates native makefiles and workspaces that can be used in the compiler environment of your choice.
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(libcurl)
    - pkgconfig(libuv)
patterns   :
    - /usr/share/cmake*
    - /usr/share/aclocal*
    - docs : /usr/share/doc
setup      : |
    # Unable to find use for jsoncpp in Solus yet, + circle deps..
    ./configure --prefix=%PREFIX% \
                --system-libs \
                --no-system-jsoncpp \
                --no-qt-gui \
                --docdir=/share/doc/cmake \
                --no-system-librhash \
                --parallel=%YJOBS%
build      : |
    %make
install    : |
    %make_install
check      : |
    export NOTEST="kwsys.testSystemTools|CTestTestUpload|CTestCoverageCollectGCOV|CTestTestSubdir"
    %make test ARGS="-E '$NOTEST'"
