name       : cmake
version    : 3.22.3
release    : 60
source     :
    - https://github.com/Kitware/CMake/releases/download/v3.22.3/cmake-3.22.3.tar.gz : 9f8469166f94553b6978a16ee29227ec49a2eb5ceb608275dec40d8ae0d1b5a0
homepage   : https://www.cmake.org/
license    : BSD-3-Clause
component  : system.devel
summary    : CMake is a cross-platform, open-source build system.
description: |
    CMake, the cross-platform, open-source make system. CMake is used to control the software compilation process using simple platform and compiler independent configuration files. CMake generates native makefiles and workspaces that can be used in the compiler environment of your choice.
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(libcurl)
    - pkgconfig(libuv)
    - python-sphinx
patterns   :
    - /usr/share/cmake*
    - /usr/share/aclocal*
    - docs : /usr/share/cmake*/Help
setup      : |
    # Unable to find use for jsoncpp in Solus yet, + circle deps..
    ./configure --prefix=%PREFIX% \
                --system-libs \
                --no-system-jsoncpp \
                --no-system-librhash \
                --no-qt-gui \
                --docdir=/share/doc/cmake \
                --mandir=/share/man \
                --sphinx-man \
                --parallel=%YJOBS%
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
check      : |
    ./bin/ctest --force-new-ctest-process -E "(CTestTestUpload|RunCMake.ParseImplicitLinkInfo|RunCMake.file-CHMOD|RunCMake.find_program|RunCMake.CommandLine)"
