name       : cmake
version    : 3.8.0
release    : 9
source     :
    - https://cmake.org/files/v3.8/cmake-3.8.0.tar.gz : cab99162e648257343a20f61bcd0b287f5e88e36fcb2f1d77959da60b7f35969
homepage   : http://www.cmake.org/
license    :
    - BSD-3-Clause
summary    : CMake is a cross-platform, open-source build system.
component  : system.devel
description: |
    CMake, the cross-platform, open-source make system. CMake is used to control the software compilation process using simple platform and compiler independent configuration files. CMake generates native makefiles and workspaces that can be used in the compiler environment of your choice.
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(libcurl)
    - pkgconfig(libuv)
patterns   :
    - /usr/share/cmake*
    - /usr/share/aclocal*
    - docs : /usr/share/doc
setup      : |
    # Unable to find use for jsoncpp in Solus yet, + circle deps..
    ./configure --prefix=/usr \
                --system-libs \
                --no-system-jsoncpp \
                --no-qt-gui \
                --docdir=/share/doc/cmake \
                --no-system-librhash \
                --parallel=%YJOBS%
build      : |
    %make
install    : |
    %make_install
