name       : cmake
version    : 3.16.1
release    : 38
source     :
    - https://github.com/Kitware/CMake/releases/download/v3.16.1/cmake-3.16.1.tar.gz : a275b3168fa8626eca4465da7bb159ff07c8c6cb0fb7179be59e12cbdfa725fd
homepage   : https://www.cmake.org/
license    : BSD-3-Clause
component  : system.devel
summary    : CMake is a cross-platform, open-source build system.
description: |
    CMake, the cross-platform, open-source make system. CMake is used to control the software compilation process using simple platform and compiler independent configuration files. CMake generates native makefiles and workspaces that can be used in the compiler environment of your choice.
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(libcurl)
    - pkgconfig(libuv)
patterns   :
    - /usr/share/cmake*
    - /usr/share/aclocal*
    - docs : /usr/share/doc
setup      : |
    # Unable to find use for jsoncpp in Solus yet, + circle deps..
    ./configure --prefix=%PREFIX% \
                --system-libs \
                --no-system-jsoncpp \
                --no-qt-gui \
                --docdir=/share/doc/cmake \
                --no-system-librhash \
                --parallel=%YJOBS%
build      : |
    %make
install    : |
    %make_install
check      : |
    export NOTEST="kwsys.testSystemTools|CTestTestUpload|CTestCoverageCollectGCOV|CTestTestSubdir"
    %make test ARGS="-E '$NOTEST'"
