name       : cmake
version    : 3.11.4
release    : 15
source     :
    - https://cmake.org/files/v3.11/cmake-3.11.4.tar.gz : 8f864e9f78917de3e1483e256270daabc4a321741592c5b36af028e72bff87f5
homepage   : https://www.cmake.org/
license    : BSD-3-Clause
component  : system.devel
summary    : CMake is a cross-platform, open-source build system.
description: |
    CMake, the cross-platform, open-source make system. CMake is used to control the software compilation process using simple platform and compiler independent configuration files. CMake generates native makefiles and workspaces that can be used in the compiler environment of your choice.
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(libcurl)
    - pkgconfig(libuv)
patterns   :
    - /usr/share/cmake*
    - /usr/share/aclocal*
    - docs : /usr/share/doc
setup      : |
    # Unable to find use for jsoncpp in Solus yet, + circle deps..
    ./configure --prefix=/usr \
                --system-libs \
                --no-system-jsoncpp \
                --no-qt-gui \
                --docdir=/share/doc/cmake \
                --no-system-librhash \
                --parallel=%YJOBS%
build      : |
    %make
install    : |
    %make_install
check      : |
    export NOTEST="kwsys.testSystemTools|CTestTestUpload|CTestCoverageCollectGCOV|CTestTestSubdir"
    %make test ARGS="-E '$NOTEST'"
